// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Track struct {
	ID                    string
	CreatedAt             string
	UpdatedAt             string
	FileName              string
	MimeType              string
	MetaAlbum             sql.NullString
	MetaAlbumArtist       sql.NullString
	MetaArtist            sql.NullString
	MetaBitrate           sql.NullInt64
	MetaDuration          sql.NullInt64
	MetaGenre             sql.NullString
	MetaIsVariableBitrate sql.NullInt64
	MetaTitle             sql.NullString
	MetaTrack             sql.NullInt64
	MetaYear              sql.NullInt64
	FileLocation          string
	FileSource            string
}
